config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/ranking' => 'homes#ranking'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 以下はユーザー
  devise_for :users, controllers: {
    registrations: "public/registrations",
    passwords: 'public/passwords',
    sessions: 'public/sessions'
  }
  scope module: 'public' do

    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'confirm'
      patch 'withdraw'
      get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'
    end

    resources :posts, only: [:new, :create, :update, :destroy, :index, :show, :edit] do
      resource :favorites, only: [:create,:destroy]
      resource :bookmarks, only: [:create,:destroy]
      resources :post_comments, only: [:create,:destroy]
    end

    resources :chats, only: [:create, :show, :index]



  end

  # 以下は管理者
  devise_for :admin, only: [:sessions, :password], :controllers => {
    :sessions => 'admin/sessions'
  }

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end

  def about
  end

  def ranking
    @post_like_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
    @post_comment_ranks = Post.find(PostComment.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container mt-5">
  <div class="row">
    <div class='mx-auto text-center'>
      <h1><i class="fas fa-shoe-prints"></i><strong>旅路</strong>　へようこそ  !!</h1>
      <p>「旅路」では、あなたの旅先、出かけた先に投稿を残すことができます。</p>
      <p>旅先での思い出、出先での発見を投稿してみませんか？</p>
    </div>
  </div>
</div>

app/views/homes/ranking.html.erb
<div class="container my-3 w-100">
  <div class="row">
    <div class="col-6 mx-auto">
      <p>いいね数ランキング</p>
      <table>
        <% @post_like_ranks.each.with_index(1) do |post, i| %>
        <div class="row">
          <div class="col-12">
            <tr>
              <td class="col-2">第<%= i %>位</td>
              <td class="col-3"><%= image_tag post.user.get_profile_image(80, 80), class:"mt-3 rounded-circle"; %></td>
              <td class="col-3">
                <%= link_to post_path(post.id) do %>
                  <%= post.title %>
                <% end %>
              </td>
              <td class="col-4"><span>いいね数：<%= post.favorites.count %></span></td>
            </tr>
          </div>
        </div>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-6 pt-3 mt-3 mx-auto border-top">
      <p>コメント数ランキング</p>
      <table>
        <% @post_comment_ranks.each.with_index(1) do |post, i| %>
        <div class="row">
          <div class="col-12">
            <tr>
              <td class="col-2">第<%= i %>位</td>
              <td class="col-3"><%= image_tag post.user.get_profile_image(80, 80), class:"mt-3 rounded-circle"; %></td>
              <td class="col-3">
                <%= link_to post_path(post.id) do %>
                  <%= post.title %>
                <% end %>
              </td>
              <td class="col-4"><span>コメント数：<%= post.post_comments.count %></span></td>
            </tr>




          </div>
        </div>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-5">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 text-center'>
      <h1>welcome to <i class="fas fa-shoe-prints"></i><strong>JOURNEY</strong>  !!</h1>
      <p>In  <i class="fas fa-shoe-prints"></i><strong>Journey</strong>, </p>
      <p>Leave records of your trip!</p>
      <p>旅行体験を記録し、他の人と共有する方法をお探しですか？</p>
      <p>もしそうなら、Journeyはあなたにぴったりの場所です。</p>
      <p>※このサイトは、随時アップデート中です。</p>
      <div class="btn-wrapper col-10 mx-auto">
        <% if user_signed_in? %>
          <p>早速投稿をしてみましょう!</p>
          <%=  link_to "投稿する！！",  new_post_path ,class: 'nav-link text-light btn btn-success btn-sm ' %>
        <% else %>
          <div class="row">
            <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>